"""Deterministic `execution_id` derivation for newly-opened trades
(ADR-008 §7: "derived from the ExecutionDecision's trace_id, generated
once per approved trade before submission").

Reuses `data_pipeline.trace.make_trace_id` — the same shared, "compute
once, share the result" deterministic-id utility Strategy Engine's
`make_candidate_id` already reuses, rather than defining a second hash
function. Since one `trace_id` may have multiple simultaneously-approved
candidates (distinct strategies firing on the same observation), the id
is derived from both `trace_id` and `candidate_id` together — the
minimal pair that uniquely identifies one approved trade.

`PositionAdjustmentRequest`/`PositionCloseRequest` (ADR-009 §5) already
carry their own `execution_id`, generated by Position Manager before
reaching this stage — this function is used only for the `OPEN` path.
"""

from __future__ import annotations

from ..data_pipeline.trace import make_trace_id


def make_execution_id(trace_id: str, candidate_id: str) -> str:
    return make_trace_id("execution", trace_id, candidate_id)
